import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#000',
  },
  chartWrap: {
    flex: 1,
    minHeight: 200,
    position: 'relative',
  },
  canvas: {
    flex: 1,
    backgroundColor: '#000',
  },
  bottomPanel: {
    flexShrink: 1,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#243028',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 14,
    backgroundColor: '#000',
  },
  hudTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  presetSwitchRow: {
    alignItems: 'stretch',
    marginBottom: 4,
  },
  presetSegmentTrack: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#324038',
    overflow: 'hidden',
    backgroundColor: '#060a08',
  },
  presetSegmentTrackLocked: {
    opacity: 0.42,
  },
  presetSegmentBtn: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#080d0a',
  },
  presetSegmentLeft: {},
  presetSegmentRight: {},
  presetSegmentBtnActive: {
    backgroundColor: '#102218',
    borderColor: '#2cff8a',
  },
  presetSegmentBtnPressed: {
    opacity: 0.88,
  },
  presetSegmentBtnDisabled: {
    opacity: 1,
  },
  presetSegmentDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: '#2a3330',
    alignSelf: 'stretch',
  },
  presetSegmentLbl: {
    color: '#7a9286',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.8,
  },
  presetSegmentLblActive: {
    color: '#bfffe0',
  },
  presetDashboardBadge: {
    marginTop: 4,
    color: '#6b9e82',
    fontSize: 9,
    letterSpacing: 0.8,
  },
  hudMetricsPanel: {
    gap: 14,
  },
  hudSection: {
    gap: 10,
  },
  hudSectionLabel: {
    color: '#5a7d68',
    fontSize: 10,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    opacity: 0.92,
  },
  hudMetricRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  performanceHint: {
    color: '#5f7d6c',
    fontSize: 10,
    lineHeight: 15,
    letterSpacing: 0.35,
  },
  performanceCard: {
    borderRadius: 11,
    backgroundColor: '#080e0c',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#284536',
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 8,
    shadowColor: '#102218',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.55,
    shadowRadius: 5,
    elevation: 4,
  },
  performanceCardTitle: {
    color: '#6d9e82',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 2.2,
  },
  performanceCardMetric: {
    color: '#c4f5dc',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  performanceAnalyzerTitle: {
    color: '#5cff9b',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 1.6,
    marginBottom: 8,
  },
  performanceCalibrationFlash: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#2cff8a',
  },
  performanceBullet: {
    color: '#86a898',
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 6,
  },
  bumpDiagCard: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: '#060a08',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#243028',
    gap: 10,
    shadowColor: '#102218',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.85,
    shadowRadius: 4,
    elevation: 3,
  },
  bumpDiagPlaceholder: {
    color: '#5f7d6c',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  bumpAdviceRowDual: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    alignItems: 'stretch',
  },
  bumpAxisCardHalf: {
    flexGrow: 1,
    flexBasis: '45%',
    minWidth: 140,
    maxWidth: '100%',
  },
  axisBumpCardTitle: {
    color: '#7ab896',
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: 2,
  },
  pitchBiasBadge: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#0f1412',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#355649',
    marginBottom: 2,
  },
  pitchBiasBadgeText: {
    color: '#b8dfc8',
    fontSize: 11,
    lineHeight: 15,
    fontStyle: 'italic',
    opacity: 0.95,
  },
  bumpDiagHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  bumpStatusChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  bumpStatusChipTxt: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  bumpPeakInline: {
    color: '#c4f5dc',
    fontSize: 14,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  bumpAdviceLine: {
    color: '#a8d4bf',
    fontSize: 12,
    lineHeight: 17,
    letterSpacing: 0.2,
  },
  bumpAdviceLbl: {
    color: '#6d8c7a',
    fontWeight: '600',
  },
  bumpDiagMeta: {
    color: '#5f7d6c',
    fontSize: 10,
    letterSpacing: 0.6,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  metricTile: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 74,
    paddingVertical: 11,
    paddingHorizontal: 10,
    borderRadius: 11,
    backgroundColor: '#060a08',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#1c2f24',
    shadowColor: '#102218',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    elevation: 3,
  },
  metricTileLabel: {
    fontSize: 9,
    letterSpacing: 0.8,
    color: '#6d8c7a',
    marginBottom: 6,
    lineHeight: 12,
  },
  metricTileVal: {
    fontSize: 17,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.2,
  },
  metricTileSuf: {
    fontSize: 12,
    fontWeight: '500',
    color: '#5f7d6c',
    opacity: 0.85,
  },
  dashboardTools: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
  },
  toolBtn: {
    padding: 6,
    borderRadius: 6,
  },
  toolBtnPressed: {
    opacity: 0.75,
  },
  toolBtnDisabled: {
    opacity: 0.35,
  },
  settingsDrawerRoot: {
    flex: 1,
  },
  settingsDrawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000',
  },
  settingsDrawerBackdropPress: {
    flex: 1,
  },
  settingsDrawerPanelWrap: {
    position: 'absolute',
  },
  settingsDrawerPanel: {
    flex: 1,
    backgroundColor: '#060a08',
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    overflow: 'hidden',
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: '#324038',
    shadowColor: '#000',
    shadowOffset: { width: 8, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 22,
    elevation: 28,
  },
  settingsDrawerEdgeLine: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: 'rgba(44, 255, 138, 0.06)',
  },
  settingsDrawerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#1e2a23',
  },
  settingsDrawerTitleBlock: {
    flex: 1,
    gap: 4,
    paddingRight: 4,
  },
  settingsDrawerTitle: {
    color: '#7ab896',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2.2,
  },
  settingsDrawerSubtitle: {
    color: '#5e6d66',
    fontSize: 9,
    letterSpacing: 0.85,
    lineHeight: 14,
  },
  settingsDrawerCloseBtn: {
    marginTop: -2,
    padding: 6,
    borderRadius: 8,
  },
  settingsDrawerCloseBtnPressed: {
    opacity: 0.72,
    backgroundColor: '#0f1814',
  },
  settingsDrawerBody: {
    flex: 1,
    minHeight: 200,
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  logoCluster: {
    justifyContent: 'flex-start',
  },
  calRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingVertical: 12,
  },
  resetMaxBtn: {
    paddingHorizontal: 6,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3a5548',
    backgroundColor: '#0a1410',
  },
  resetMaxBtnDisabled: {
    opacity: 0.35,
  },
  resetMaxBtnPressed: {
    opacity: 0.88,
  },
  resetMaxLabel: {
    color: '#8a9e94',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1.2,
  },
  logo: {
    color: '#5cff9b',
    fontSize: 15,
    letterSpacing: 2,
    fontWeight: '700',
    marginBottom: -2,
  },
  logoSub: {
    color: '#5a6b63',
    fontSize: 8,
    letterSpacing: 1.4,
    marginBottom: 2,
  },
  calBtn: {
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2cff8a',
    overflow: 'visible',
  },
  calBtnDisabled: {
    opacity: 0.35,
  },
  calBanner: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.72)',
    zIndex: 4,
  },
  calBannerText: {
    color: '#9effc5',
    fontSize: 13,
    letterSpacing: 1,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  calPrecOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 8, 4, 0.82)',
    zIndex: 6,
    paddingHorizontal: 18,
    gap: 18,
  },
  calPrecTitle: {
    color: '#5cff9b',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2,
    textAlign: 'center',
  },
  calPrecTrack: {
    width: '88%',
    maxWidth: 460,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(44, 255, 138, 0.1)',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(44, 255, 138, 0.38)',
  },
  calModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.84)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  calModalCard: {
    width: '100%',
    maxWidth: 400,
    paddingVertical: 32,
    paddingHorizontal: 22,
    borderRadius: 14,
    backgroundColor: '#0a1210',
    borderWidth: 1,
    borderColor: '#2cff8a',
    gap: 22,
    alignItems: 'center',
  },
  calModalProgressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(44, 255, 138, 0.12)',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(44, 255, 138, 0.4)',
    alignSelf: 'center',
  },
  calBtnPressed: {
    opacity: 0.88,
  },
  calGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 32,
    shadowColor: '#2cff8a',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: -4 },
    elevation: 15,
  },
  calLabel: {
    color: '#6cffb0',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 2,
  },
  terrainIcon: {
    fontSize: 28,
    textShadowColor: 'rgba(0,0,0,0.85)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  hfTelemetryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    paddingBottom: 8,
  },
  hfJsonRecBtn: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#14080a',
    borderWidth: 1.5,
    borderColor: '#aa4460',
    minWidth: 100,
    alignItems: 'center',
  },
  hfJsonRecBtnOn: {
    backgroundColor: '#2a0610',
    borderColor: '#ff2150',
  },
  hfJsonRecBtnDisabled: {
    opacity: 0.35,
  },
  hfJsonRecBtnPressed: {
    opacity: 0.88,
  },
  hfJsonRecLabel: {
    color: '#ff9aad',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  hfJsonExportBtn: {
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#0a1210',
    borderWidth: 1,
    borderColor: '#5a8cff',
    minWidth: 100,
    alignItems: 'center',
  },
  hfJsonExportBtnDisabled: {
    opacity: 0.35,
  },
  hfJsonExportBtnPressed: {
    opacity: 0.88,
  },
  hfJsonExportLabel: {
    color: '#9ec5ff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
  ecuScreenTitle: {
    color: '#5cff9b',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 2.4,
  },
  ecuConnectBtn: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2cff8a',
    overflow: 'visible',
    backgroundColor: '#060c09',
  },
  ecuConnectBtnScanning: {
    borderColor: '#48eaff',
    shadowColor: '#48eaff',
    shadowOpacity: 0.55,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 12,
  },
  ecuConnectBtnConnected: {
    borderColor: '#5cff9b',
    backgroundColor: '#0a1810',
    shadowColor: '#2cff8a',
    shadowOpacity: 0.65,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 14,
  },
  ecuConnectBtnError: {
    borderColor: '#ff6b82',
    shadowColor: '#ff6b82',
    shadowOpacity: 0.4,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
  },
  ecuConnectGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 8,
    shadowColor: '#2cff8a',
    shadowOpacity: 0.75,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: -2 },
    elevation: 10,
  },
  ecuConnectLabel: {
    color: '#6cffb0',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.6,
  },
  ecuConnectLabelScanning: {
    color: '#8ae8ff',
  },
  ecuConnectLabelConnected: {
    color: '#9effc5',
  },
  ecuConnectLabelError: {
    color: '#ffb3bf',
  },
  ecuInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 4,
  },
  ecuInfoKey: {
    color: '#6d8c7a',
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: '600',
  },
  ecuInfoVal: {
    color: '#c4f5dc',
    fontSize: 11,
    fontWeight: '600',
    flexShrink: 1,
    textAlign: 'right',
    fontVariant: ['tabular-nums'],
  },
});
