import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#000',
  },
  chartWrap: {
    flex: 1,
    minHeight: 200,
    position: 'relative',
  },
  canvas: {
    flex: 1,
    backgroundColor: '#000',
  },
  bottomPanel: {
    flexShrink: 1,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#243028',
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 14,
    backgroundColor: '#000',
  },
  hudTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  presetSwitchRow: {
    alignItems: 'stretch',
    marginBottom: 4,
  },
  presetSegmentTrack: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#324038',
    overflow: 'hidden',
    backgroundColor: '#060a08',
  },
  presetSegmentTrackLocked: {
    opacity: 0.42,
  },
  presetSegmentBtn: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#080d0a',
  },
  presetSegmentLeft: {},
  presetSegmentRight: {},
  presetSegmentBtnActive: {
    backgroundColor: '#102218',
    borderColor: '#2cff8a',
  },
  presetSegmentBtnPressed: {
    opacity: 0.88,
  },
  presetSegmentBtnDisabled: {
    opacity: 1,
  },
  presetSegmentDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: '#2a3330',
    alignSelf: 'stretch',
  },
  presetSegmentLbl: {
    color: '#7a9286',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.8,
  },
  presetSegmentLblActive: {
    color: '#bfffe0',
  },
  presetDashboardBadge: {
    marginTop: 4,
    color: '#6b9e82',
    fontSize: 9,
    letterSpacing: 0.8,
  },
  hudMetricsPanel: {
    gap: 14,
  },
  hudSection: {
    gap: 10,
  },
  hudSectionLabel: {
    color: '#5a7d68',
    fontSize: 10,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    opacity: 0.92,
  },
  hudMetricRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  bumpDiagCard: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 11,
    backgroundColor: '#060a08',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#243028',
    gap: 10,
    shadowColor: '#102218',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.85,
    shadowRadius: 4,
    elevation: 3,
  },
  bumpDiagPlaceholder: {
    color: '#5f7d6c',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  bumpDiagHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  bumpStatusChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
  },
  bumpStatusChipTxt: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  bumpPeakInline: {
    color: '#c4f5dc',
    fontSize: 14,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  bumpAdviceLine: {
    color: '#a8d4bf',
    fontSize: 12,
    lineHeight: 17,
    letterSpacing: 0.2,
  },
  bumpAdviceLbl: {
    color: '#6d8c7a',
    fontWeight: '600',
  },
  bumpDiagMeta: {
    color: '#5f7d6c',
    fontSize: 10,
    letterSpacing: 0.6,
    marginTop: 2,
    fontVariant: ['tabular-nums'],
  },
  metricTile: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 74,
    paddingVertical: 11,
    paddingHorizontal: 10,
    borderRadius: 11,
    backgroundColor: '#060a08',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#1c2f24',
    shadowColor: '#102218',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    elevation: 3,
  },
  metricTileLabel: {
    fontSize: 9,
    letterSpacing: 0.8,
    color: '#6d8c7a',
    marginBottom: 6,
    lineHeight: 12,
  },
  metricTileVal: {
    fontSize: 17,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.2,
  },
  metricTileSuf: {
    fontSize: 12,
    fontWeight: '500',
    color: '#5f7d6c',
    opacity: 0.85,
  },
  dashboardTools: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
  },
  toolBtn: {
    padding: 6,
    borderRadius: 6,
  },
  toolBtnPressed: {
    opacity: 0.75,
  },
  toolBtnDisabled: {
    opacity: 0.35,
  },
  advancedPanel: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#2a3330',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    backgroundColor: '#050805',
  },
  advancedTitle: {
    color: '#5e6d66',
    fontSize: 10,
    letterSpacing: 1.2,
  },
  logoCluster: {
    justifyContent: 'flex-start',
  },
  calRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingVertical: 12,
  },
  resetMaxBtn: {
    paddingHorizontal: 6,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3a5548',
    backgroundColor: '#0a1410',
  },
  resetMaxBtnDisabled: {
    opacity: 0.35,
  },
  resetMaxBtnPressed: {
    opacity: 0.88,
  },
  resetMaxLabel: {
    color: '#8a9e94',
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 1.2,
  },
  logo: {
    color: '#5cff9b',
    fontSize: 15,
    letterSpacing: 2,
    fontWeight: '700',
    marginBottom: -2,
  },
  logoSub: {
    color: '#5a6b63',
    fontSize: 8,
    letterSpacing: 1.4,
    marginBottom: 2,
  },
  calBtn: {
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2cff8a',
    overflow: 'visible',
  },
  calBtnDisabled: {
    opacity: 0.35,
  },
  calBanner: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.72)',
    zIndex: 4,
  },
  calBannerText: {
    color: '#9effc5',
    fontSize: 13,
    letterSpacing: 1,
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  calBtnPressed: {
    opacity: 0.88,
  },
  calGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 32,
    shadowColor: '#2cff8a',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: -4 },
    elevation: 15,
  },
  calLabel: {
    color: '#6cffb0',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 2,
  },
  hfTelemetryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
    paddingBottom: 8,
  },
  hfJsonRecBtn: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#14080a',
    borderWidth: 1.5,
    borderColor: '#aa4460',
    minWidth: 100,
    alignItems: 'center',
  },
  hfJsonRecBtnOn: {
    backgroundColor: '#2a0610',
    borderColor: '#ff2150',
  },
  hfJsonRecBtnDisabled: {
    opacity: 0.35,
  },
  hfJsonRecBtnPressed: {
    opacity: 0.88,
  },
  hfJsonRecLabel: {
    color: '#ff9aad',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  hfJsonExportBtn: {
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#0a1210',
    borderWidth: 1,
    borderColor: '#5a8cff',
    minWidth: 100,
    alignItems: 'center',
  },
  hfJsonExportBtnDisabled: {
    opacity: 0.35,
  },
  hfJsonExportBtnPressed: {
    opacity: 0.88,
  },
  hfJsonExportLabel: {
    color: '#9ec5ff',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
  },
});
